- id: git-clang-format
  name: git-clang-format
  description: clang-format your C, C++, or C# code
  entry: git clang-format
  language: python
  types_or: [c++, c, c#, cuda]
  minimum_pre_commit_version: 2.9.2
